### PR TITLE
[ol] - add tags feature

### PR DESCRIPTION
**Pull request by OrlandoLee**
using act_as_taggable gem to add tags to users and projects

Screen Shot 2020-03-18 at 8 55 04 AM
Screen Shot 2020-03-18 at 8 54 35 AM
Screen Shot 2020-03-18 at 8 54 17 AM
Screen Shot 2020-03-18 at 8 54 00 AM
Screen Shot 2020-03-18 at 8 53 53 AM

### CODE REVIEW

**Comment by OrlandoLee** [comment]
@sradu  PTAL

**Comment by OrlandoLee** [comment]
@sradu just added search functionality as well but no UI  you can search by something like this 
 http://localhost:3000/projects?skill=software

**Comment by vcavallo** [comment]
Closes https://github.com/sradu/covid-volunteers/issues/8

**Comment by vcavallo** [comment]
@OrlandoLee Do you need some help adding the search UI? I could potentially take that.

**Comment by sradu** [comment]
@vcavallo if you have time do it!

**Pull request merged**
